-- TABLA DE LOGS PARA CAZAR EL ERROR
CREATE TABLE IF NOT EXISTS public.debug_logs (
    id bigint generated by default as identity primary key,
    message text,
    details jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Permisos
ALTER TABLE public.debug_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read logs" ON public.debug_logs FOR SELECT USING (true);
CREATE POLICY "Public insert logs" ON public.debug_logs FOR INSERT WITH CHECK (true);

-- TRIGGER A PRUEBA DE BOMBAS
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  v_rol text;
  v_nombre text;
  v_codigo text;
BEGIN
  -- Extraer valores con seguridad
  v_rol := COALESCE(new.raw_user_meta_data ->> 'rol', 'alumno');
  v_nombre := COALESCE(new.raw_user_meta_data ->> 'nombre', new.raw_user_meta_data ->> 'full_name', 'Usuario');
  v_codigo := COALESCE(new.raw_user_meta_data ->> 'codigo_sala', null);

  BEGIN
    -- Intentar Insertar Normal
    INSERT INTO public.profiles (id, email, rol, full_name, codigo_sala)
    VALUES (new.id, new.email, v_rol, v_nombre, v_codigo)
    ON CONFLICT (id) DO UPDATE
    SET 
      rol = excluded.rol,
      full_name = excluded.full_name,
      codigo_sala = excluded.codigo_sala,
      email = excluded.email;
      
  EXCEPTION WHEN OTHERS THEN
    -- Si falla, LOGUEAR EL ERROR y no abortar
    INSERT INTO public.debug_logs (message, details)
    VALUES (
      'Error en handle_new_user', 
      jsonb_build_object(
        'error', SQLERRM, 
        'user_id', new.id, 
        'rol_intentado', v_rol
      )
    );
    
    -- INTENTO DE FALLBACK (Inserción Mínima)
    BEGIN
      INSERT INTO public.profiles (id, email, rol)
      VALUES (new.id, new.email, 'alumno') -- Fallback a alumno si rol es el problema
      ON CONFLICT (id) DO NOTHING;
    EXCEPTION WHEN OTHERS THEN
       -- Si falla el fallback, ya es grave, pero al menos el log quedó.
       NULL;
    END;
  END;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recrear Trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
