-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Rol de usuario)
-- Se vincula automáticamente con auth.users mediante trigger
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  rol text check (rol in ('profesor', 'alumno')) default 'alumno',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PROYECTOS
create table public.proyectos (
  id uuid default uuid_generate_v4() primary key,
  nombre text not null,
  descripcion text,
  tipo text, -- 'Radio/Podcast', 'Video/YouTube', etc.
  estado text check (estado in ('En curso', 'Finalizado', 'En preparación')),
  codigo_sala text unique,
  clase text, -- '5ºA', '6ºB', etc.
  fases jsonb default '[]'::jsonb, -- Array de fases {id, nombre, estado}
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- GRUPOS
create table public.grupos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  departamento text,
  miembros jsonb default '[]'::jsonb, -- Array de strings con nombres
  progreso integer default 0,
  estado text check (estado in ('En progreso', 'Casi terminado', 'Completado', 'Bloqueado')),
  interacciones_ia integer default 0,
  proyecto_id uuid references public.proyectos(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MENSAJES DE CHAT (Historial IA)
create table public.mensajes_chat (
  id bigint generated by default as identity primary key,
  grupo_id bigint references public.grupos(id) on delete cascade,
  usuario_id uuid references public.profiles(id),
  tipo text check (tipo in ('user', 'assistant', 'system')),
  contenido text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ALUMNOS CONECTADOS (Real-time presence)
create table public.alumnos_conectados (
  id uuid default uuid_generate_v4() primary key,
  proyecto_id uuid references public.proyectos(id) on delete cascade,
  nombre_alumno text not null,
  last_active timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) - Políticas de seguridad básicas
alter table public.profiles enable row level security;
alter table public.proyectos enable row level security;
alter table public.grupos enable row level security;
alter table public.mensajes_chat enable row level security;
alter table public.alumnos_conectados enable row level security;

-- Política: Todos pueden leer todo (para simplificar en este MVP)
create policy "Public access" on public.profiles for all using (true);
create policy "Public access" on public.proyectos for all using (true);
create policy "Public access" on public.grupos for all using (true);
create policy "Public access" on public.mensajes_chat for all using (true);
create policy "Public access" on public.alumnos_conectados for all using (true);

-- TRIGGER PARA CREAR PERFIL AUTOMÁTICAMENTE AL REGISTRARSE
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, rol)
  values (new.id, new.email, 'profesor'); -- Por defecto profesor para este dashboard
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- DATOS DE EJEMPLO (Opcional, para poblar la BD inicial)
-- Puedes ejecutar esto después de crear tu usuario para asignarle proyectos
